[versions]
kotlin = "2.1.20"
ksp = "2.1.20-1.0.31"
koin-annotations = "2.0.0"
snake-yaml = "2.2"
spotless = "7.0.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
ksp-symbol-processing = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
snake-yaml = { module = "org.yaml:snakeyaml", version.ref = "snake-yaml" }
